test('checks the top 10 economical bowlers in 2015', () => {
  const top10EconomicalBowlersYear2015 = require('../server/top-10-economical-bowlers-in-2015.js');

  const sampleDataMatches = [
    {
      id: '1',
      season: '2015',
      winner: 'Kolkata Knight Riders',
    },
    {
      id: '2',
      season: '2015',
      winner: 'Mumbai Indians',
    },
    {
      id: '3',
      season: '2015',
      winner: 'Mumbai Indians',
    },
    {
      id: '4',
      season: '2015',
      winner: 'Rajasthan Royals',
    },
    {
      id: '5',
      season: '2015',
      winner: 'Royal Challengers Bangalore',
    },
    {
      id: '6',
      season: '2015',
      winner: 'Royal Challengers Bangalore',
    },
    {
      id: '7',
      season: '2015',
      winner: 'Royal Challengers Bangalore',
    },
    {
      id: '8',
      season: '2015',
      winner: 'Royal Challengers Bangalore',
    },
    {
      id: '9',
      season: '2015',
      winner: 'Royal Challengers Bangalore',
    },
    {
      id: '10',
      season: '2015',
      winner: 'Royal Challengers Bangalore',
    },
    {
      id: '11',
      season: '2015',
      winner: 'Royal Challengers Bangalore',
    },
    {
      id: '12',
      season: '2015',
      winner: 'Royal Challengers Bangalore',
    },
    {
      id: '13',
      season: '2015',
      winner: 'Royal Challengers Bangalore',
    },
    {
      id: '14',
      season: '2015',
      winner: 'Royal Challengers Bangalore',
    },
  ];

  const sampleDataDeliveries = [
    {
      match_id: '1',
      bowling_team: 'Kolkata Knight Riders',
      bowler: 'R Ashwin',
      batsman_runs: 2,
      total_runs: 2,
      wide_runs: 0,
      noball_runs: 0,
    },
    {
      match_id: '2',
      extra_runs: 0,
      bowling_team: 'Mumbai Indians',
      bowler: 'S Narine',
      batsman_runs: 1,
      total_runs: 1,
      wide_runs: 0,
      noball_runs: 0,
    },
    {
      match_id: '3',
      extra_runs: 1,
      bowling_team: 'Mumbai Indians',
      bowler: 'R Ashwin',
      batsman_runs: 0,
      total_runs: 0,
      wide_runs: 0,
      noball_runs: 0,
    },
    {
      match_id: '4',
      extra_runs: 0,
      bowling_team: 'Rajasthan Royals',
      bowler: 'S Narine',
      batsman_runs: 4,
      total_runs: 4,
      wide_runs: 0,
      noball_runs: 0,
    },
    {
      match_id: '5',
      extra_runs: 0,
      bowling_team: 'Royal Challengers Bangalore',
      bowler: 'S Narine',
      batsman_runs: 1,
      total_runs: 1,
      wide_runs: 0,
      noball_runs: 0,
    },
    {
      match_id: '6',
      extra_runs: 0,
      bowling_team: 'Royal Challengers Bangalore',
      bowler: 'Umesh',
      batsman_runs: 0,
      total_runs: 1,
      wide_runs: 1,
      noball_runs: 0,
    },
    {
      match_id: '7',
      extra_runs: 4,
      bowling_team: 'Royal Challengers Bangalore',
      bowler: 'Umesh',
      batsman_runs: 2,
      total_runs: 2,
      wide_runs: 0,
      noball_runs: 0,
    },
    {
      match_id: '8',
      extra_runs: 4,
      bowling_team: 'Royal Challengers Bangalore',
      bowler: 'M Shami',
      batsman_runs: 2,
      total_runs: 2,
      wide_runs: 0,
      noball_runs: 0,
    },
    {
      match_id: '9',
      extra_runs: 0,
      bowling_team: 'Royal Challengers Bangalore',
      bowler: 'Siraj',
      batsman_runs: 0,
      total_runs: 0,
      wide_runs: 0,
      noball_runs: 0,
    },
    {
      match_id: '10',
      extra_runs: 0,
      bowling_team: 'Royal Challengers Bangalore',
      bowler: 'V Kohli',
      batsman_runs: 2,
      total_runs: 2,
      wide_runs: 0,
      noball_runs: 0,
    },
    {
      match_id: '11',
      extra_runs: 0,
      bowling_team: 'Royal Challengers Bangalore',
      bowler: 'R Chahal',
      batsman_runs: 3,
      total_runs: 3,
      wide_runs: 0,
      noball_runs: 0,
    },
    {
      match_id: '12',
      extra_runs: 0,
      bowling_team: 'Royal Challengers Bangalore',
      bowler: 'Bumrah',
      batsman_runs: 1,
      total_runs: 1,
      wide_runs: 0,
      noball_runs: 0,
    },
    {
      match_id: '13',
      extra_runs: 4,
      bowling_team: 'Royal Challengers Bangalore',
      bowler: 'Kuldeep',
      batsman_runs: 2,
      total_runs: 2,
      wide_runs: 0,
      noball_runs: 0,
    },
    {
      match_id: '14',
      extra_runs: 0,
      bowling_team: 'Royal Challengers Bangalore',
      bowler: 'R Sharma',
      batsman_runs: 2,
      total_runs: 2,
      wide_runs: 0,
      noball_runs: 0,
    },
  ];

  let actualResult = [
    ['Siraj', '0.00'],
    ['Bumrah', '6.00'],
    ['R Ashwin', '6.00'],
    ['Kuldeep', '12.00'],
    ['M Shami', '12.00'],
    ['R Sharma', '12.00'],
    ['S Narine', '12.00'],
    ['V Kohli', '12.00'],
    ['R Chahal', '18.00'],
    ['Umesh', '18.00'],
  ];

  let receivedResult = top10EconomicalBowlersYear2015(
    sampleDataMatches,
    sampleDataDeliveries,
  );
  expect(actualResult).toEqual(receivedResult);
});
